import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { SidebarItem } from "@/components/Sidebar";
import {
  LifeBuoy,
  Receipt,
  Boxes,
  Package,
  UserCircle,
  BarChart3,
  LayoutDashboard,
  Settings,
  LogIn,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Sidebar>
          <SidebarItem
            icon={<LayoutDashboard size={20} />}
            text="Dashboard"
            href="/dashboard"
            alert
          />
          <SidebarItem
            icon={<BarChart3 size={20} />}
            text="Statistics"
            href="/statistics"
          />
          <SidebarItem icon={<LifeBuoy size={20} />} text="Stocks" href="/stocks" />
          <SidebarItem icon={<Boxes size={20} />} text="Banking" href="/banking" />
          <SidebarItem icon={<Package size={20} />} text="Backtest" href="/backtest" />
          <SidebarItem icon={<Receipt size={20} />} text="Billings" href="/billings" />
          <hr className="my-3" />
          <SidebarItem icon={<Settings size={20} />} text="Settings" href="/settings" />
          <SidebarItem icon={<LogIn size={20} />} text="Log In" href="/log-in" />
          <SidebarItem icon={<UserCircle size={20} />} text="User" href="/user" />
        </Sidebar>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
